function createfigure(X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 30-Dec-2017 16:05:02

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'FontSize',20,'FontName','Times New Roman');
%% Uncomment the following line to preserve the X-limits of the axes
xlim(axes1,[37.4 38.6]);
%% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes1,[0 0.0171842105263158]);
box(axes1,'on');
hold(axes1,'all');

% Create plot
plot(X1,Y1);

% Create title
title({''});

% Create xlabel
xlabel('f (kHz)','FontWeight','bold','FontSize',24,...
    'FontName','Times New Roman');

% Create ylabel
ylabel('|FT(f)|','FontWeight','bold','FontSize',24,...
    'FontName','Times New Roman');

